{{- if .Values.global.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "automation-domain-layer.selectorLabels" . | nindent 4 }}
    environment: {{ .Values.global.environment | quote }}
{{- end }}
