{{- if .Values.configService.enabled }}
{{ include "automation-service-layer.renderService" (dict "root" $ "service" .Values.configService "name" "config-service" "component" "backend") }}
{{- end }}
