version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}    
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${DATABASE_NAME}      
    ports:
      - "5432:5432"              
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
