global:
  namespace: automation-preprod
  createNamespace: false
  environment: preprod

commonEnv:
  api: {}
  mock: {}

apiRouter:
  enabled: true

mockRouter:
  enabled: true
  defaultPlaygroundUrl: "http://playground-mock-service:3000/mock/playground/"

domains: []
