name: REDIS_DEPLOYMENT_STAGING

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
          name: staging
          url: https://github.com    

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Host to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Redis Container with Custom User Authentication
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} bash -c "
            if sudo docker inspect -f '{{.State.Running}}' redis-cache-staging &>/dev/null; then
              sudo docker stop redis-cache-staging && sudo docker rm redis-cache-staging
            fi
            
            # acl file has been created at /tmp/redis-users.acl make sure it is created beforehand
            # it contains user and password data
            
            # Deploy Redis container with the ACL file
            sudo docker run -d \
              --name redis-cache-staging \
              -p ${vars.REDIS_PORT_STAGING}:6379 \
              -v /tmp/redis-users.acl:/usr/local/etc/redis-users.acl \
              redis:latest \
              redis-server --aclfile /usr/local/etc/redis-users.acl
          "
        env:
          REDIS_USERNAME: ${{ vars.REDIS_USERNAME }}
          REDIS_PASSWORD: ${{ vars.REDIS_PASSWORD }}